import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import NavBar from '../components/NavBar/NavBar';
import {Data} from '../components/DataJson/Data'
import fakeCategories from "../categories";
import fakePosts from "../posts";

export default function Home() {
  const handleClick = (e) => {
    if(e) e.preventDefault();
    console.log(e,'eeeeee')
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      {/* <main className={styles.main}>
      {/* {Data.map((e) => (
        <div key={e.id} style={{border: '1px solid grey', padding: '10px', margin: '10px', display: 'flex', flexFlow: 'row wrap ', width:'25%',cursor:'pointer'}}>
            <a  href={'Contact/'+ e.id} >
               <>
                <div> {e.id}</div>
                <span>{e.category}</span>
                <div> {e.price}</div>
                <div> {e.product}</div>
                <img  src={e.image} width={200} height={100}/>
                </>
            </a>
        </div>
        )
      )} 
        <h1>صفحه اصلی</h1>
        <h2>محصولات فروشگاه ما</h2>
      <ol>
          {Data.map((post) => (
            <li key={post.id}>
              <Link href={`/Contact/[id]`} as={`/Contact/${post.Slug}`}>
                <a>{post.Title}</a>
              </Link>
              <img alt='i' src={post.image} width={200} height={100}/>
            </li>
          ))}
      </ol>
      </main> */}
      <header>
        <h1>Home</h1>
      </header>
      <main>
        <section>
          <h2>Categories</h2>
          <ul>
            {fakeCategories.map((category) => (
              <li key={category.Id}>
                <Link href={`/${category.Slug}`}>
                  <a>{category.Name}</a>
                </Link>
              </li>
            ))}
          </ul>
        </section>

        <section>
          <h2>All Posts</h2>
          <ol>
            {fakePosts.map((post) => (
              <li key={post.Id}>
                <Link href={`/post/${post.Slug}`}>
                  <a>{post.Title}</a>
                </Link>
              </li>
            ))}
          </ol>
        </section>
      </main>
    
    <footer className="footer block-dark mt-n15 mt-lg-n30">

		
	  </footer>
  
    </div>
  )
}
